export default class Home {
	constructor() {
		this.handleFormSubmit();
		this.handleInputChangeFinishEditing();
	}

	/**
	 * Handle the 'calculate' button press, so that we can show a custom, more pretty response.
	 */
	private handleFormSubmit(): void {
		$(document).on('submit', '#calculation-form', function () {
			const form = $(this);

			console.log(form.attr('action'));

			$.ajax({
				url: form.attr('action'), // The action (generated by asp)
				type: 'POST',
				data: form.serialize(), // Data from the form
				success(response) {
					console.log(response);
				}
			});
			return false;
		});
	}

	/**
	 * When the inputs are clicked off, this corrects the values to 2DP.
	 */
	private handleInputChangeFinishEditing(): void {
		$(document).on('focusout', '#calculation-form input', function () {
			$(this).val(parseFloat(($(this).val() as string) ?? '0').toFixed(2));
		});
	}
}
