export default class Home {
	constructor() {
		console.log('todo');
	/**
	 * Handle the 'calculate' button press, so that we can show a custom, more pretty response.
	 */
	private handleFormSubmit(): void {
		$(document).on('submit', '#calculation-form', function () {
			const form = $(this);

			console.log(form.attr('action'));

			$.ajax({
				url: form.attr('action'), // The action (generated by asp)
				type: 'POST',
				data: form.serialize(), // Data from the form
				success(response) {
					console.log(response);
				}
			});
			return false;
		});
	}
	}
}
